version: '3'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/mydb
    links:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: